### ISSUE TITLE
[BUG] buyerIdentityUpdate function update deliveryAddressPreferences object in checkout

### ISSUE THREAD

**Issue by samuelsalter** [Shopify/hydrogen-ui#92]
**Describe the bug**
Using the buyerIdentityUpdate function from the useCart hook, doesn't respect the deliveryAddressPreferences object entered.

**To Reproduce**

1. Call function with values
```
buyerIdentityUpdate({
      countryCode: 'GB',
      email: 'test@example.com',
      phone: '123412344',
      deliveryAddressPreferences: [{
        deliveryAddress: {
          address1: '1',
          address2: '2',
          city: 'London',
          country: 'GB',
          firstName: 'Test',
          lastName: 'Example',
          phone: '123412344',
          zip: 'SW12 1JG',
          province: 'London',
        }
      }]
 })
```
2. Go to the checkout link, either via component or fetch checkoutUrl from hook
3. Note shipping address is empty

**Expected behavior**
Shipping address to be populated

**Screenshots**

**Additional context**

- Hydrogen UI version: 2022.10.5
- Framework used: NextJS
- Node version: v16.18.0
- Browser: Chrome 108.0.5359.98

**Comment by frehner** [comment]
Ok, looking into it, just taking some notes mostly for myself. 

It seems that the `cartBuyerIdentityUpdate` is generally just meant for you to get accurate pricing info for the customer's cart. https://shopify.dev/api/storefront/2022-10/mutations/cartBuyerIdentityUpdate

We do keep the `checkoutUrl` in state in one location (`useInstantCheckout()`), but otherwise we just get the URL from the response from the Storefront API. I think.

I don't think the Storefront API supports returning that info at the moment, so if we decide to do something, it would have to be done in our library directly (or by writing guides on how to augment the checkout url with that information). See also https://github.com/Shopify/storefront-api-feedback/discussions/55

---

So I guess the question is, do we want to add something to this library to help with this use case, or ask that the Storefront API support it, or some other options? @elisenyang thoughts?

**Comment by elisenyang** [comment]
@frehner this seems like something we should bring to the SF API team first so let's do that before we implement anything
